image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - lint
  - test
  - build
  - deploy

before_script:
  - npm install

lint_job:
  stage: lint
  script:
    - npm run lint

test_job:
  stage: test
  script:
    - npm run test

build_job:
  stage: build
  script:
    - npm run build

deploy_production:
  stage: deploy
  environment: Production
  only:
    - main
  script:
    - npm install -g firebase-tools
    - firebase use --token $FIREBASE_DEPLOY_KEY production
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY
