export const MATERIAL_ICONS_LIST: Record<string, string> = {
  'storefront': 'Storefront',
  'apartment': 'Apartment',
  'fitness_center': 'Fitness Center',
  'business_center': 'Business Center',
  'spa': 'Spa',
  'house': 'House',
  'meeting_room': 'Meeting Room',
  'corporate_fare': 'Corporate Fare',
  'ac_unit': 'Ac Unit',
  'cottage': 'Cottage',
  'family_restroom': 'Family Restroom',
  'other_houses': 'Other Houses',
  'checkroom': 'Checkroom',
  'grass': 'Grass',
  'all_inclusive': 'All Inclusive',
  'airport_shuttle': 'Airport Shuttle',
  'child_care': 'Child Care',
  'beach_access': 'Beach Access',
  'pool': 'Pool',
  'kitchen': 'Kitchen',
  'casino': 'Casino',
  'holiday_village': 'Holiday Village',
  'roofing': 'Roofing',
  'room_service': 'Room Service',
  'room_preferences': 'Room Preferences',
  'sports_bar': 'Sports Bar',
  'free_breakfast': 'Free Breakfast',
  'bathtub': 'Bathtub',
  'escalator_warning': 'Escalator Warning',
  'child_friendly': 'Child Friendly',
  'foundation': 'Foundation',
  'food_bank': 'Food Bank',
  'gite': 'Gite',
  'villa': 'Villa',
  'night_shelter': 'Night Shelter',
  'golf_course': 'Golf Course',
  'no_photography': 'No Photography',
  'stairs': 'Stairs',
  'microwave': 'Microwave',
  'backpack': 'Backpack',
  'elevator': 'Elevator',
  'smoking_rooms': 'Smoking Rooms',
  'wash': 'Wash',
  'cabin': 'Cabin',
  'house_siding': 'House Siding',
  'hot_tub': 'Hot Tub',
  'countertops': 'Countertops',
  'water_damage': 'Water Damage',
  'fire_extinguisher': 'Fire Extinguisher',
  'carpenter': 'Carpenter',
  'charging_station': 'Charging Station',
  'baby_changing_station': 'Baby Changing Station',
  'soap': 'Soap',
  'rv_hookup': 'Rv Hookup',
  'umbrella': 'Umbrella',
  'smoke_free': 'Smoke Free',
  'tapas': 'Tapas',
  'rice_bowl': 'Rice Bowl',
  'do_not_touch': 'Do Not Touch',
  'balcony': 'Balcony',
  'no_food': 'No Food',
  'tty': 'Tty',
  'fence': 'Fence',
  'houseboat': 'Houseboat',
  'bento': 'Bento',
  'wheelchair_pickup': 'Wheelchair Pickup',
  'iron': 'Iron',
  'bungalow': 'Bungalow',
  'chalet': 'Chalet',
  'crib': 'Crib',
  'do_not_step': 'Do Not Step',
  'no_meeting_room': 'No Meeting Room',
  'escalator': 'Escalator',
  'dry': 'Dry',
  'stroller': 'Stroller',
  'no_drinks': 'No Drinks',
  'no_cell': 'No Cell',
  'no_flash': 'No Flash',
  'no_backpack': 'No Backpack',
  'no_stroller': 'No Stroller',
  'vaping_rooms': 'Vaping Rooms',
  'desk': 'Desk',
  'vape_free': 'Vape Free',
};
