export interface Icon {
  code: string;
  label: string;
}

export const MATERIAL_ICONS: Icon[] = [
  { code: 'storefront', label: 'Storefront' },
  { code: 'apartment', label: 'Apartment' },
  { code: 'fitness_center', label: 'Fitness Center' },
  { code: 'business_center', label: 'Business Center' },
  { code: 'spa', label: 'Spa' },
  { code: 'house', label: 'House' },
  { code: 'meeting_room', label: 'Meeting Room' },
  { code: 'corporate_fare', label: 'Corporate Fare' },
  { code: 'ac_unit', label: 'Ac Unit' },
  { code: 'cottage', label: 'Cottage' },
  { code: 'family_restroom', label: 'Family Restroom' },
  { code: 'other_houses', label: 'Other Houses' },
  { code: 'checkroom', label: 'Checkroom' },
  { code: 'grass', label: 'Grass' },
  { code: 'all_inclusive', label: 'All Inclusive' },
  { code: 'airport_shuttle', label: 'Airport Shuttle' },
  { code: 'child_care', label: 'Child Care' },
  { code: 'beach_access', label: 'Beach Access' },
  { code: 'pool', label: 'Pool' },
  { code: 'kitchen', label: 'Kitchen' },
  { code: 'casino', label: 'Casino' },
  { code: 'holiday_village', label: 'Holiday Village' },
  { code: 'roofing', label: 'Roofing' },
  { code: 'room_service', label: 'Room Service' },
  { code: 'room_preferences', label: 'Room Preferences' },
  { code: 'sports_bar', label: 'Sports Bar' },
  { code: 'free_breakfast', label: 'Free Breakfast' },
  { code: 'bathtub', label: 'Bathtub' },
  { code: 'escalator_warning', label: 'Escalator Warning' },
  { code: 'child_friendly', label: 'Child Friendly' },
  { code: 'foundation', label: 'Foundation' },
  { code: 'food_bank', label: 'Food Bank' },
  { code: 'gite', label: 'Gite' },
  { code: 'villa', label: 'Villa' },
  { code: 'night_shelter', label: 'Night Shelter' },
  { code: 'golf_course', label: 'Golf Course' },
  { code: 'no_photography', label: 'No Photography' },
  { code: 'stairs', label: 'Stairs' },
  { code: 'microwave', label: 'Microwave' },
  { code: 'backpack', label: 'Backpack' },
  { code: 'elevator', label: 'Elevator' },
  { code: 'smoking_rooms', label: 'Smoking Rooms' },
  { code: 'wash', label: 'Wash' },
  { code: 'cabin', label: 'Cabin' },
  { code: 'house_siding', label: 'House Siding' },
  { code: 'hot_tub', label: 'Hot Tub' },
  { code: 'countertops', label: 'Countertops' },
  { code: 'water_damage', label: 'Water Damage' },
  { code: 'fire_extinguisher', label: 'Fire Extinguisher' },
  { code: 'carpenter', label: 'Carpenter' },
  { code: 'charging_station', label: 'Charging Station' },
  { code: 'baby_changing_station', label: 'Baby Changing Station' },
  { code: 'soap', label: 'Soap' },
  { code: 'rv_hookup', label: 'Rv Hookup' },
  { code: 'umbrella', label: 'Umbrella' },
  { code: 'smoke_free', label: 'Smoke Free' },
  { code: 'tapas', label: 'Tapas' },
  { code: 'rice_bowl', label: 'Rice Bowl' },
  { code: 'do_not_touch', label: 'Do Not Touch' },
  { code: 'balcony', label: 'Balcony' },
  { code: 'no_food', label: 'No Food' },
  { code: 'tty', label: 'Tty' },
  { code: 'fence', label: 'Fence' },
  { code: 'houseboat', label: 'Houseboat' },
  { code: 'bento', label: 'Bento' },
  { code: 'wheelchair_pickup', label: 'Wheelchair Pickup' },
  { code: 'iron', label: 'Iron' },
  { code: 'bungalow', label: 'Bungalow' },
  { code: 'chalet', label: 'Chalet' },
  { code: 'crib', label: 'Crib' },
  { code: 'do_not_step', label: 'Do Not Step' },
  { code: 'no_meeting_room', label: 'No Meeting Room' },
  { code: 'escalator', label: 'Escalator' },
  { code: 'dry', label: 'Dry' },
  { code: 'stroller', label: 'Stroller' },
  { code: 'no_drinks', label: 'No Drinks' },
  { code: 'no_cell', label: 'No Cell' },
  { code: 'no_flash', label: 'No Flash' },
  { code: 'no_backpack', label: 'No Backpack' },
  { code: 'no_stroller', label: 'No Stroller' },
  { code: 'vaping_rooms', label: 'Vaping Rooms' },
  { code: 'desk', label: 'Desk' },
  { code: 'vape_free', label: 'Vape Free' },
];
